INSERT INTO TODO (NAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES
('sri', 'GET QT CERTIFIED', CURRENT_DATE(), FALSE),
('sri', 'GET AOSP CERTIFIED', CURRENT_DATE(), FALSE),
('mahy', 'GET FULLSTACK DEVELOPER CERTIFIED', CURRENT_DATE(), FALSE),
('mahy', 'GET MOBILE DEVELOPER CERTIFIED', CURRENT_DATE(), FALSE)
;

