INSERT INTO TODO (ID, NAME, DESCRIPTION, TARGET_DATE, DONE) 
VALUES
(1001, 'SRI', 'GET QT CERTIFIED', CURRENT_DATE(), FALSE),
(1002, 'SRI', 'GET AOSP CERTIFIED', CURRENT_DATE(), FALSE),
(1003, 'MAHY', 'GET FULLSTACK DEVELOPER CERTIFIED', CURRENT_DATE(), FALSE),
(1004, 'MAHY', 'GET MOBILE DEVELOPER CERTIFIED', CURRENT_DATE(), FALSE)
;